#3/new main view UI
DeveloperAcademy-POSTECH/MacC-Team12-Creative8 pull request #18
Opened 2023-10-16 04:55 UTC by sumintnals

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- #3/newMainViewUI

👷 **작업한 내용**
- 상단 배너
- 아카이빙 콘서트 목록
- 다가오는 콘서트 목록
- 인기 아티스트 목록

## 🚨 참고 사항
- 

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|전체 GIF| ![Simulator Screen Recording - iPhone 15 Pro - 2023-10-16 at 01 08 07](https://github.com/DeveloperAcademy-POSTECH/MacC-Team12-Creative8/assets/127755029/8ca61748-a71e-4458-ab0a-b672a5f2e17d)|

## 📟 관련 이슈
- Resolved: #

2023-10-16 15:53 UTC, Oreo-Mcflurry reviewed
렌조 수고하셨습니당~

2023-10-16 15:53 UTC, Oreo-Mcflurry commented on MainBookmarkedView.swift
> +                    .padding(.bottom)
p3
이런거 .padding([.leading, .bottom]) 이런식으로 하나로 묶으면 전체적인 코드 길이가 줄어서 가독성 측면에서 좋을거에용

2023-10-16 15:53 UTC, Oreo-Mcflurry commented on MainBookmarkedView.swift
> +}
p1
이건 무엇인가요? 아무런 버튼 스타일이 지정이 안되어있는데 안쓰는 버튼 스타일이라면 지우는게 좋을거같아요

2023-10-16 15:53 UTC, Oreo-Mcflurry commented on PopularArtistView.swift
> +                            .frame(width: screenWidth * 0.44, height: screenHeight * 0.16)
p5
이런것들 따로 뺴서 some View로 빼주면 더 좋은 코드가 될거에요.
이런식으로 따로 빼주는 이유는 코드 가독성을 위해 이렇게 하는건데,
https://www.youtube.com/watch?v=sXiD-2XrkKQ
이 영상 55:50부터 보면, 스탠포드 대학 교수님이 본인이 쓴 코드 정리하는법을 보여주세요.
이 영상보고 공부하면 좋을거같아요~
```
private var imageExample: some View {
Image(image)
    .resizable()
    .clipShape(RoundedRectangle(cornerRadius: 20))
    .frame(width: screenWidth * 0.44, height: screenHeight * 0.16)
}
```

2023-10-16 15:53 UTC, Oreo-Mcflurry commented on TopBannerView.swift
> +                        selection = "배너를 눌렀다"
p2
이거 뭐에요?  ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
근데, NavigationLink를 tag써서 하는거, iOS15이상 부터는 권장되지 않는 방법일텐데,
보통 tagt식 네비게이션 링크가 하나만 필요하다면 
```
 .navigationDestination(isPresented: $bindingBool, destination: ContentView())
```
이런식으로 구현 하거나, 여러개라면
```
@State private var test: Int?

  var body: some View {
    NavigationStack {
      List {
        Button("Mint") { test = 1 }
        Button("Pink") { test = 2 }
        Button("Teal") { test = 3 }
      }
      .navigationDestination(item: $test) { index in
        if index == 1 { AnotherView1() }
        else if index == 2 { AnotherView2() }
        else { AnotherView3() }
      }
    }
  }
```
이런식으로 구현할 수도 있겠죠.

2023-10-17 11:14 UTC, wonniiii requested changes
고생하셨어요 렌조! 리뷰 확인해주시고 고쳐서 다시 push 부탁드려요 !

2023-10-17 11:14 UTC, wonniiii commented on MainBookmarkedView.swift
> +        }
p3
이 부분은 어떤 기능을 하는 함수들인가요?

2023-10-17 11:14 UTC, wonniiii commented on MainBookmarkedView.swift
> +    let image: String
p2
mvvm 아키텍처에 의하면 이 친구들은 따로 데이터 모델로 따로 빼서 관리하는게 더 좋아보여요. 
모델 파일 하나 만들어서
```
struct MainBookMarkData {
    let id: Int
    let singer: String
    let concertName: String
    let dDay: String
    let month: String
    let day: String
    let image: String
}
```
이런식으로 만들고 MainViewModel에서 

```
class MainViewModel: ObservableObject {
    @Published var MainBookMarkData: MainBookMarkData

   init(MainBookMarkData: MainBookMarkData) {
        self.MainBookMarkData = MainBookMarkData
    } ..
}
```
이런식으로 선언해주고, 뷰에서는 뷰모델 선언해주고
`  Text(viewModel.MainBookMarkData.dDay)
` 이런식으로 호출하면 됩니당

2023-10-17 11:14 UTC, wonniiii commented on PopularArtistView.swift
> +    let venue3: String
p2
이 친구들도 MainBookMarkedView에서 말했던 것처럼 바꾸는게 좋아보여요

2023-10-17 11:14 UTC, wonniiii commented on PopularArtistView.swift
> +                        )
p2
이 뷰가 밑에서도 똑같이 쓰이는데, 따로 빼서 재활용하는게 더 좋아보여요

2023-10-17 11:14 UTC, wonniiii commented on MainBookmarkedView.swift
> +                Text("")
p1
여기 비어있는 텍스트는 왜 넣으신건가용??

2023-10-17 11:14 UTC, wonniiii commented on TopBannerView.swift
> +                        print("이거되나?")
p1
필요 없는 print문은 빼주세용

2023-10-17 11:14 UTC, wonniiii commented on TopBannerView.swift
> +                    .padding(.trailing)
p1
이 부분은 위에 Spcer()있어서 없어도 아무 변화가 없더라구요. 지워도 될 것 같아용

2023-10-19 07:29 UTC, closed without merging